version: "3.7"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - pg12_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  pg12_data:
